package carl.ui;

import java.io.IOException;

import javafx.beans.binding.Bindings;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.geometry.Pos;
import javafx.scene.control.Label;
import javafx.scene.layout.HBox;

/**
 * Represents a responsive chat bubble for the user, Carl, or an error message.
 */
public class DialogBox extends HBox {
    @FXML
    private Label dialog;
    @FXML
    private Label speaker;

    private DialogBox(String text, DialogType type) {
        try {
            FXMLLoader fxmlLoader = new FXMLLoader(Ui.class.getResource("/view/DialogBox.fxml"));
            fxmlLoader.setController(this);
            fxmlLoader.setRoot(this);
            fxmlLoader.load();
        } catch (IOException e) {
            e.printStackTrace();
        }

        dialog.setText(text);
        getStyleClass().add(type.styleClass);
        setAlignment(type.alignment);
        setMaxWidth(Double.MAX_VALUE);

        speaker.setText(type.heading);
        speaker.setManaged(type.showsHeading);
        speaker.setVisible(type.showsHeading);

        // Keep messages readable on wide windows without overflowing narrow ones.
        dialog.maxWidthProperty().bind(Bindings.min(560,
                Bindings.max(180, widthProperty().multiply(type.widthRatio).subtract(36))));
    }

    /**
     * Creates a compact green bubble for text entered by the user.
     *
     * @param text text entered by the user
     * @return a user-styled dialog box
     */
    public static DialogBox getUserDialog(String text) {
        return new DialogBox(text, DialogType.USER);
    }

    /**
     * Creates a neutral response bubble for Carl.
     *
     * @param text response generated by Carl
     * @return a bot-styled dialog box
     */
    public static DialogBox getBotDialog(String text) {
        return new DialogBox(text, DialogType.BOT);
    }

    /**
     * Creates a high-contrast red bubble for invalid commands and other command errors.
     *
     * @param text error message generated by Carl
     * @return an error-styled dialog box
     */
    public static DialogBox getErrorDialog(String text) {
        return new DialogBox(text, DialogType.ERROR);
    }

    /**
     * Defines the visual treatment and responsive width of each message category.
     */
    private enum DialogType {
        USER("user-dialog", "", Pos.TOP_RIGHT, false, 0.72),
        BOT("bot-dialog", "CARL", Pos.TOP_LEFT, true, 0.82),
        ERROR("error-dialog", "COMMAND ERROR", Pos.TOP_LEFT, true, 0.86);

        private final String styleClass;
        private final String heading;
        private final Pos alignment;
        private final boolean showsHeading;
        private final double widthRatio;

        DialogType(String styleClass, String heading, Pos alignment,
                   boolean showsHeading, double widthRatio) {
            this.styleClass = styleClass;
            this.heading = heading;
            this.alignment = alignment;
            this.showsHeading = showsHeading;
            this.widthRatio = widthRatio;
        }
    }
}
